# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/miru/Documents/IEP/Proiect/iepProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/miru/Documents/IEP/Proiect/iepProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miru/Documents/IEP/Proiect/iepProject/CMakeFiles /home/miru/Documents/IEP/Proiect/iepProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/miru/Documents/IEP/Proiect/iepProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named artGallery

# Build rule for target.
artGallery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 artGallery
.PHONY : artGallery

# fast build rule for target.
artGallery/fast:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/build
.PHONY : artGallery/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/paint.o: src/paint.cpp.o

.PHONY : src/paint.o

# target to build an object file
src/paint.cpp.o:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/paint.cpp.o
.PHONY : src/paint.cpp.o

src/paint.i: src/paint.cpp.i

.PHONY : src/paint.i

# target to preprocess a source file
src/paint.cpp.i:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/paint.cpp.i
.PHONY : src/paint.cpp.i

src/paint.s: src/paint.cpp.s

.PHONY : src/paint.s

# target to generate assembly for a file
src/paint.cpp.s:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/paint.cpp.s
.PHONY : src/paint.cpp.s

src/painter.o: src/painter.cpp.o

.PHONY : src/painter.o

# target to build an object file
src/painter.cpp.o:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painter.cpp.o
.PHONY : src/painter.cpp.o

src/painter.i: src/painter.cpp.i

.PHONY : src/painter.i

# target to preprocess a source file
src/painter.cpp.i:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painter.cpp.i
.PHONY : src/painter.cpp.i

src/painter.s: src/painter.cpp.s

.PHONY : src/painter.s

# target to generate assembly for a file
src/painter.cpp.s:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painter.cpp.s
.PHONY : src/painter.cpp.s

src/painting.o: src/painting.cpp.o

.PHONY : src/painting.o

# target to build an object file
src/painting.cpp.o:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painting.cpp.o
.PHONY : src/painting.cpp.o

src/painting.i: src/painting.cpp.i

.PHONY : src/painting.i

# target to preprocess a source file
src/painting.cpp.i:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painting.cpp.i
.PHONY : src/painting.cpp.i

src/painting.s: src/painting.cpp.s

.PHONY : src/painting.s

# target to generate assembly for a file
src/painting.cpp.s:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/painting.cpp.s
.PHONY : src/painting.cpp.s

src/surface.o: src/surface.cpp.o

.PHONY : src/surface.o

# target to build an object file
src/surface.cpp.o:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/surface.cpp.o
.PHONY : src/surface.cpp.o

src/surface.i: src/surface.cpp.i

.PHONY : src/surface.i

# target to preprocess a source file
src/surface.cpp.i:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/surface.cpp.i
.PHONY : src/surface.cpp.i

src/surface.s: src/surface.cpp.s

.PHONY : src/surface.s

# target to generate assembly for a file
src/surface.cpp.s:
	$(MAKE) -f CMakeFiles/artGallery.dir/build.make CMakeFiles/artGallery.dir/src/surface.cpp.s
.PHONY : src/surface.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... artGallery"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/paint.o"
	@echo "... src/paint.i"
	@echo "... src/paint.s"
	@echo "... src/painter.o"
	@echo "... src/painter.i"
	@echo "... src/painter.s"
	@echo "... src/painting.o"
	@echo "... src/painting.i"
	@echo "... src/painting.s"
	@echo "... src/surface.o"
	@echo "... src/surface.i"
	@echo "... src/surface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

